=== mrgjha/MyCollegeTimeWork/xsltx/sample27.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2000/10/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xsd:complexType name="Item">
		<xsd:annotation>
			<xsd:documentation>Individual Item Entry</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name="ItemName" type="xsd:string"/>
			<xsd:element name="ItemNum">
				<xsd:simpleType>
					<xsd:restriction base="xsd:string">
						<xsd:pattern value=".\d\d-\d\d"/>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:element>
			<xsd:element name="ItemDesc" type="xsd:string"/>
			<xsd:element name="ItemCost" type="xsd:decimal"/>
			<xsd:element name="ItemLocation">
				<xsd:simpleType>
					<xsd:restriction base="xsd:string">
						<xsd:enumeration value="Chicago"/>
						<xsd:enumeration value="SanDiego"/>
						<xsd:enumeration value="Over-seas"/>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:element>
			<xsd:element name="NumInStock" type="xsd:int"/>
		</xsd:sequence>
		<xsd:attribute name="LastUpdated" type="xsd:date" use="required"/>
	</xsd:complexType>
	<xsd:complexType name="Inventory">
		<xsd:annotation>
			<xsd:documentation>Inventory list - root element</xsd:documentation>
		</xsd:annotation>
		<xsd:all>
			<xsd:element name="ItemInfo" minOccurs="0" maxOccurs="unbounded"/>
		</xsd:all>
	</xsd:complexType>
	<xsd:element name="InvList" type="Inventory"/>
	<xsd:element name="ItemInfo" type="Item"/>
</xsd:schema>

=== mrgjha/MyCollegeTimeWork/xsltx/sample.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XML Spy v3.5 (http://www.xmlspy.com) by Heather de Leon (Wagonboss.net) -->
<?xml-stylesheet type="text/xsl" href="sample.xsl"?>
<InvList xmlns:xsi="http://www.w3.org/2000/10/XMLSchema-instance" xsi:noNamespaceSchemaLocation="D:\Osborn-McGraw\XML-ComRef\Chapter27\sample27.xsd">
	<ItemInfo LastUpdated="2005-02-01">
		<ItemName>Widget Works Pro</ItemName>
		<ItemNum>W22-34</ItemNum>
		<ItemDesc>This is the perfect Widget for all major projects.</ItemDesc>
		<ItemCost>14.55</ItemCost>
		<ItemLocation>Chicago</ItemLocation>
		<NumInStock>2345</NumInStock>
	</ItemInfo>
	<ItemInfo LastUpdated="2004-12-09">
		<ItemName>Widget Basics</ItemName>
		<ItemNum>W22-03</ItemNum>
		<ItemDesc>Widget for smaller jobs.</ItemDesc>
		<ItemCost>9.06</ItemCost>
		<ItemLocation>SanDiego</ItemLocation>
		<NumInStock>123333</NumInStock>
	</ItemInfo>
	<ItemInfo LastUpdated="2003-13-19">
		<ItemName>Widget Regular</ItemName>
		<ItemNum>W22-19</ItemNum>
		<ItemDesc>Widget for the majority of jobs you will encounter</ItemDesc>
		<ItemCost>12.34</ItemCost>
		<ItemLocation>Over-seas</ItemLocation>
		<NumInStock>40325</NumInStock>
	</ItemInfo>
</InvList>
